configName: pic32mz_w1_curiosity_freertos
folderName: pic32mz_w1_curiosity_freertos
format_version: v1.0
frameworkPath: ..\..\rio2_ofc_repo
processor: PIC32MZ1025W104132
projectName: wifi_ota_app_upgrade_pic32mz_w1_curiosity_freertos
settings:
  PackageFilter: bsp;core;crypto;csp;csp_apps_pic32mz_w1;net;quick_docs;usb;wireless;wireless;wsg_dev;wsg_dev;wsg_dev;wsg_dev;wsg_dev;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.7.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\PIC32MZ-W_DFP\1.3.177\atdf\PIC32MZ1025W104132.atdf
