configName: pic32mzw1
folderName: ''
format_version: v1.0
frameworkPath: ../../../..
processor: PIC32MZ1025W104132
projectName: ''
settings:
  PackageFilter: bsp;core;crypto;csp;csp_apps_pic32mz_w1;net;quick_docs;usb;wireless;wsg_dev;wsg_dev;wsg_dev;wsg_dev;wsg_dev;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.7.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\PIC32MZ-W_DFP\1.3.177\atdf\PIC32MZ1025W104132.atdf
