format_version: v1.0
type: UniqueComponent
attributes: {id: spi1}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: SPI_BRG_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: spi1, value: '49'}
  - type: KeyValueSet
    attributes: {id: SPI_SPICON_MSSEN}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
- type: Attachments
  children:
  - type: DirectCapability
    attributes: {id: SPI1_SPI}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: appPic32mzw1OtaBtl}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: SPI_OTA_Bootloader_Dependency}
- type: ElementPosition
  attributes: {x: '340', y: '96', id: spi1}
